# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15ChGDWzUuAwM-15ps_lQJ0P0AopnKmYl
"""

import ipywidgets as widgets
from IPython.display import display, clear_output
import pymongo
from pymongo import MongoClient
import sys
import random


client = MongoClient('mongodb+srv://aris:1234@cluster0.5ss2jng.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0')

db = client['SGRP_BDNR']
collection = db['movies']


# Definir las opciones para cada menú desplegable
opciones_1 = [("+18 únicamente", "+18 únicamente"), ("Apto para todas las edades", "Apto para todas las edades"), ("Todo", "Todo")]
opciones_2 = [("Antiguas", "Antiguas"), ("Estreno", "Estreno"), ("Indiferente", "Indiferente")]
opciones_sexo = [("Masculino", "Masculino"), ("Femenino", "Femenino")]
opciones_generos = [("Action", False), ("Adventure", False), ("Animation", False), ("Biography", False), ("Comedy", False), ("Crime", False), ("Drama", False), ("Family", False), ("Fantasy", False), ("History", False), ("Horror", False), ("Musical", False), ("Mystery", False), ("Noir", False), ("Romance", False), ("Sport", False), ("Sci-Fi", False), ("Thriller", False), ("War", False), ("Western", False)]
opciones_popularidad = [("Prefiero las más populares", "Populares"), ("Prefiero descubrirlas por mi mismo", "NOPopulares")]
opciones_aficionado = [("Experto", "Experto"), ("Aficionado", "Aficionado"), ("Ocasional","Ocasional"), ("Muy ocasional", "Muy ocasional")]
opciones_duracion = [("Plan fascinante","Plan fascinante"), ("Agobiante","Agobiante"), ("Irrelevante","Irrelevante")]

# Crear los widgets de los menús desplegables
menu_desplegable_1 = widgets.Dropdown(
    options=opciones_1,
    value=None
)

menu_desplegable_2 = widgets.Dropdown(
    options=opciones_2,
    value=None
)

widget_edad = widgets.Text(
    placeholder='Escribe tu edad aquí'
)

menu_sexo = widgets.Dropdown(
    options=opciones_sexo,
    value=None
)

menu_popularidad = widgets.Dropdown(
    options=opciones_popularidad,
    value=None
)

menu_aficionado = widgets.Dropdown(
    options=opciones_aficionado,
    value=None
)

menu_duracion = widgets.Dropdown(
    options=opciones_duracion,
    value=None
)

widgets_toggle = [widgets.ToggleButton(description=label, value=valor, layout=widgets.Layout(width='auto', height='auto')) for label, valor in opciones_generos]

pressed = False

def on_button_click(cambio):
    global pressed
    pressed = True

button = widgets.Button(description="¡Dame otra película!")

# Mostrar los widgets en el notebook
print("¿Que edad tiene?")
display(widget_edad)
print("¿Cual es su género?")
display(menu_sexo)
print("¿Cómo de fanático al mundo cinematográfico se considera?")
display(menu_aficionado)
print("¿Cómo le gusta la idea de pasar una tarde entera viendo películas?")
display(menu_duracion)
print("Seleccione aquellos géneros de su preferencia: \n(El valor recomendado es 3, un número menor podría fallar)")
grid = widgets.GridBox(widgets_toggle, layout=widgets.Layout(grid_template_columns="repeat(4, 150px)"))
display(grid)
print("¿Le gustan las películas +18 años o aptas para todas las edades?")
display(menu_desplegable_1)
print("¿Prefiere películas aclamadas por el público o aquellas menos conocidas?")
display(menu_popularidad)
print("¿Prefiere películas antiguas o de estreno?")
display(menu_desplegable_2)

# Variables para almacenar las opciones seleccionadas
edad = 0
antiguedad = None
generos_recomendados = []
grupoedad = None
sexo = None
seleccionadas = []
popularidad = None
aficionado = None
duracion = None
peliculas_mostradas = []

# Funciones para manejar la selección de cada menú desplegable
def funcion_registro_edad(cambio):
    global edad
    edad = int(cambio.new)

def funcion_restriccion_edad(cambio):
    global grupoedad
    grupoedad = cambio.new

def funcion_aficionado(cambio):
    global aficionado
    aficionado = cambio.new

def funcion_duracion(cambio):
    global duracion
    duracion = cambio.new

def manejar_toggle_button(change):
    global seleccionadas
    seleccionadas = [widget.description for widget in widgets_toggle if widget.value]

def funcion_popularidad(cambio):
    global popularidad
    popularidad = cambio.new

def funcion_sexo(cambio):
    global sexo
    sexo = cambio.new

def funcion_antiguedad(cambio):
    global antiguedad
    antiguedad = cambio.new

    ejecutar_consulta()

# Función para ejecutar la consulta
def ejecutar_consulta():
    consulta = {}

    if edad < 13:
        consulta["ratings"] = {"$in": ["G", "PG", "TV-PG"]}
        consulta["Genres"] = {"$in": ["Action", "Family", "Animation", "Adventure", "Comedy", "Fantasy", "Musical", "Sport"]}
        consulta["year"] = {"$gt": "2005"}
        consulta["duration"] = {"$lte": 120}

    if 13 <= edad <= 17:
        consulta["ratings"] = {"$in": ["Approved", "G", "PG", "TV-PG", "PG-13"]}
        consulta["year"] = {"$gt": "2000"}
        consulta["duration"] = {"$lte": 120}
        consulta["popularity"] = {"$gt": 30000}

    if 18 <= edad <= 29:
        consulta["popularity"] = {"$gt": 50000}
        consulta["calification"] = {"$gt": "6.5"}
        consulta["metacritic_score"] = {"$gt": "40"}
        consulta["year"] = {"$gt": "1980"}

    if 30 <= edad <= 50:
        consulta["calification"] = {"$gt": "7.0"}
        consulta["metacritic_score"] = {"$gt": "65"}
        consulta["year"] = {"$lt": "2015", "$gt": "1975"}

    if edad >= 50:
        consulta["calification"] = {"$gt": "6.0"}
        consulta["metacritic_score"] = {"$gt": "50"}
        consulta["year"] = {"$lt": "2000"}
        consulta["duration"] = {"$lte": 120}

    if sexo == 'Femenino':
        generos_recomendados.append('Romance')
        generos_recomendados.append('Comedia')
        generos_recomendados.append('Thriller')

    if sexo == 'Masculino':
        generos_recomendados.append('Sci-')
        generos_recomendados.append('Action')

    if edad >= 13:
        for genero_usuario in seleccionadas:
            if genero_usuario == "Sci-Fi":
                genero_usuario = "Sci-"
            if genero_usuario not in generos_recomendados:
                generos_recomendados.append(genero_usuario)
            if genero_usuario == "Noir":
                consulta["year"] = {"$lt": "1980"}

    consulta["Genres"] = {"$in": generos_recomendados}

    if aficionado == 'Experto':
        consulta["$or"] = [
            {"calification": {"$gte": "7.5"}},
            {"metacritic_score": {"$gt": "89"}}
        ]
        consulta["popularity"] = {"$lt": 100000}

    if aficionado == 'Aficionado':
        consulta["$or"] = [
            {"calification": {"$gte": "7.0"}},
            {"metacritic_score": {"$gt": "85"}}
        ]
        consulta["popularity"] = {"$gte": 150000}

    if aficionado == 'Ocasional':
        consulta["$or"] = [
            {"calification": {"$gte": "6.0"}},
            {"metacritic_score": {"$gt": "60"}}
        ]
        consulta["popularity"] = {"$gte": 300000}
        consulta["year"] = {"$gte": "1990"}

    if aficionado == 'Muy ocasional':
        consulta["$or"] = [
            {"calification": {"$gte": "7.0"}},
            {"metacritic_score": {"$gt": "75"}}
        ]
        consulta["popularity"] = {"$gte": 400000}
        consulta["year"] = {"$gte": "2000"}

    if duracion == "Plan fascinante":
        consulta["duration"] = {"$gte": 130}

    if duracion == "Agobiante":
        consulta["duration"] = {"$lte": 125}

    if popularidad == 'Populares':
        if edad < 13:
            consulta["ratings"] = {"$in": ["G", "PG", "TV-PG"]}
            consulta["Genres"] = {"$in": ["Action", "Family", "Animation", "Adventure", "Comedy", "Fantasy", "Musical", "Sport"]}
            consulta["popularity"] = {"$gt": 90000}
        else:
            consulta["popularity"] = {"$gt": 300000}

    if popularidad == 'NOPopulares':
        if aficionado == "Experto":
            consulta["popularity"] = {"$lte": 100000}
        else:
            consulta["popularity"] = {"$lte": 300000}

    if edad < 18 and grupoedad == '+18 únicamente':
        print("Usted es menor de 18 años y no puede acceder a películas para adultos.")
        if edad < 13:
            consulta["ratings"] = {"$in": ["G", "PG", "TV-PG"]}
            consulta["Genres"] = {"$in": ["Action", "Family", "Animation", "Adventure", "Comedy", "Fantasy", "Musical", "Sport"]}
        else:
            consulta["ratings"] = {"$in": ["Approved", "G", "PG", "TV-PG", "PG-13"]}

    if edad < 18 and grupoedad == 'Todo':
        print("Usted es menor de 18 años y no puede acceder a películas para adultos.")
        if edad < 13:
            consulta["ratings"] = {"$in": ["G", "PG", "TV-PG"]}
            consulta["Genres"] = {"$in": ["Action", "Family", "Animation", "Adventure", "Comedy", "Fantasy", "Musical", "Sport"]}
        else:
            consulta["ratings"] = {"$in": ["Approved", "G", "PG", "TV-PG", "PG-13"]}

    if edad >= 18 and grupoedad == '+18 únicamente':
        consulta["ratings"] = {"$in": ["R", "NC-17", "TV-MA", "Not Rated", 0]}

    if edad >= 18 and grupoedad == 'Todo':
        consulta["ratings"] = {"$in": ["Approved", "G", "PG", "TV-PG", "PG-13", "R", "NC-17", "TV-MA", "Not Rated", 0]}

    if grupoedad == 'Apto para todas las edades':
        if edad < 13:
            consulta["ratings"] = {"$in": ["G", "PG", "TV-PG"]}
            consulta["Genres"] = {"$in": ["Action", "Family", "Animation", "Adventure", "Comedy", "Fantasy", "Musical", "Sport"]}
        else:
            consulta["ratings"] = {"$in": ["Approved", "G", "PG", "TV-PG", "PG-13"]}

    if edad < 45 and antiguedad == 'Antiguas':
      if edad < 13:
            consulta["ratings"] = {"$in": ["G", "PG", "TV-PG"]}
            consulta["Genres"] = {"$in": ["Action", "Family", "Animation", "Adventure", "Comedy", "Fantasy", "Musical", "Sport"]}
            consulta["year"] = {"$lt": "2000"}
      else:
            consulta["year"] = {"$lt": "1980"}
            consulta["metacritic_score"] = {"$in": 0}
            consulta["metacritic_score"] = {"$gte": "0"}
            consulta["popularity"] = {"$gte": 0}

    if edad >= 45 and antiguedad == 'Antiguas':
        consulta["year"] = {"$lt": "1960"}
        consulta["metacritic_score"] = {"$in": 0}
        consulta["metacritic_score"] = {"$gte": "0"}
        consulta["popularity"] = {"$gte": 0}

    if antiguedad == 'Estreno':
        consulta["year"] = {"$gte": "2020"}

    resultados = collection.find(consulta)

    resultados_lista = list(resultados)

    if resultados_lista:
        peliculas_disponibles = [pelicula for pelicula in resultados_lista if pelicula["name"] not in peliculas_mostradas]
        if peliculas_disponibles:
            pelicula_aleatoria = random.choice(peliculas_disponibles)
            print("Película recomendada:")
            print("- ", pelicula_aleatoria["name"])
            print("\nSinopsis:")
            print(pelicula_aleatoria["description"])
            peliculas_mostradas.append(pelicula_aleatoria["name"])
            display(button)
        else:
            print("Ya no hay más películas disponibles que coincidan con los criterios de búsqueda.")
    else:
        print("No se encontraron películas que coincidan con los criterios de búsqueda.")

# Registrar las funciones de manejo para los eventos de cambio de selección
widget_edad.observe(funcion_registro_edad, names='value')
menu_sexo.observe(funcion_sexo, names='value')
menu_aficionado.observe(funcion_aficionado, names='value')
menu_duracion.observe(funcion_duracion, names='value')
for widget in widgets_toggle:
    widget.observe(manejar_toggle_button, 'value')
menu_desplegable_1.observe(funcion_restriccion_edad, names='value')
menu_popularidad.observe(funcion_popularidad, names='value')
menu_desplegable_2.observe(funcion_antiguedad, names='value')

clear_output(wait=True)  # Limpiar la salida de la consola

def on_button_click(button):
    clear_output(wait=True)
    ejecutar_consulta()

button.on_click(on_button_click)